# Generated by Django 4.2.7 on 2023-12-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_event_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='free_places',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_place_limited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='places',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(to='event_app.category'),
        ),
    ]
