# Generated by Django 4.2.7 on 2023-12-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_category_event_free_places_event_is_place_limited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='event_app.category'),
        ),
    ]
