# Generated by Django 4.2.7 on 2023-12-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploader_app', '0003_alter_imagetesttable_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetesttable',
            name='img_url',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='imagetesttable',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
